version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosec
    - nilerr
    - nilnil
    - bodyclose
    - errorlint
    - misspell
    - unconvert
    - unparam
    - revive
  settings:
    staticcheck:
      # Enable all staticcheck checks
      checks: ["all"]
  exclusions:
    rules:
      - path: _test\.go
        linters: [errcheck]

formatters:
  enable:
    - gofumpt
    - goimports
