version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: vault
    main: ./cmd/vault
    binary: vault
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: vault
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat.*:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix.*:'
      order: 1
    - title: Others
      order: 999

brews:
  - name: vault
    repository:
      owner: choplin
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: .
    homepage: https://github.com/vault-md/vaultmd
    description: "vault.md - A knowledge vault for AI-assisted development"
    license: MIT
    install: |
      bin.install "vault"
    test: |
      system "#{bin}/vault", "--version"
