// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry_status.sql

package sqldb

import (
	"context"
	"database/sql"
)

const DeleteEntryStatus = `-- name: DeleteEntryStatus :execrows
DELETE FROM entry_status
WHERE entry_id = ?
`

func (q *Queries) DeleteEntryStatus(ctx context.Context, entryID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteEntryStatus, entryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const FindEntryStatusByEntryID = `-- name: FindEntryStatusByEntryID :one
SELECT entry_id, is_archived, current_version, updated_at
FROM entry_status
WHERE entry_id = ?
LIMIT 1
`

func (q *Queries) FindEntryStatusByEntryID(ctx context.Context, entryID int64) (EntryStatus, error) {
	row := q.db.QueryRowContext(ctx, FindEntryStatusByEntryID, entryID)
	var i EntryStatus
	err := row.Scan(
		&i.EntryID,
		&i.IsArchived,
		&i.CurrentVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertEntryStatus = `-- name: InsertEntryStatus :exec
INSERT INTO entry_status (entry_id, is_archived, current_version)
VALUES (?, ?, ?)
`

type InsertEntryStatusParams struct {
	EntryID        int64         `json:"entry_id"`
	IsArchived     sql.NullInt64 `json:"is_archived"`
	CurrentVersion sql.NullInt64 `json:"current_version"`
}

func (q *Queries) InsertEntryStatus(ctx context.Context, arg InsertEntryStatusParams) error {
	_, err := q.db.ExecContext(ctx, InsertEntryStatus, arg.EntryID, arg.IsArchived, arg.CurrentVersion)
	return err
}

const UpdateEntryStatusArchived = `-- name: UpdateEntryStatusArchived :execrows
UPDATE entry_status
SET is_archived = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE entry_id = ?
`

type UpdateEntryStatusArchivedParams struct {
	IsArchived sql.NullInt64 `json:"is_archived"`
	EntryID    int64         `json:"entry_id"`
}

func (q *Queries) UpdateEntryStatusArchived(ctx context.Context, arg UpdateEntryStatusArchivedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateEntryStatusArchived, arg.IsArchived, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateEntryStatusCurrentVersion = `-- name: UpdateEntryStatusCurrentVersion :exec
UPDATE entry_status
SET current_version = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE entry_id = ?
`

type UpdateEntryStatusCurrentVersionParams struct {
	CurrentVersion sql.NullInt64 `json:"current_version"`
	EntryID        int64         `json:"entry_id"`
}

func (q *Queries) UpdateEntryStatusCurrentVersion(ctx context.Context, arg UpdateEntryStatusCurrentVersionParams) error {
	_, err := q.db.ExecContext(ctx, UpdateEntryStatusCurrentVersion, arg.CurrentVersion, arg.EntryID)
	return err
}
