// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry.sql

package sqldb

import (
	"context"
	"database/sql"
)

const DeleteEntriesByScope = `-- name: DeleteEntriesByScope :execrows
DELETE FROM entries
WHERE scope_id = ?
`

func (q *Queries) DeleteEntriesByScope(ctx context.Context, scopeID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteEntriesByScope, scopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteEntryByID = `-- name: DeleteEntryByID :execrows
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntryByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteEntryByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const FindEntryByID = `-- name: FindEntryByID :one
SELECT id, scope_id, key, created_at
FROM entries
WHERE id = ?
LIMIT 1
`

func (q *Queries) FindEntryByID(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, FindEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.Key,
		&i.CreatedAt,
	)
	return i, err
}

const FindEntryByScopeAndKey = `-- name: FindEntryByScopeAndKey :one
SELECT id, scope_id, key, created_at
FROM entries
WHERE scope_id = ? AND key = ?
LIMIT 1
`

type FindEntryByScopeAndKeyParams struct {
	ScopeID int64  `json:"scope_id"`
	Key     string `json:"key"`
}

func (q *Queries) FindEntryByScopeAndKey(ctx context.Context, arg FindEntryByScopeAndKeyParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, FindEntryByScopeAndKey, arg.ScopeID, arg.Key)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.Key,
		&i.CreatedAt,
	)
	return i, err
}

const InsertEntry = `-- name: InsertEntry :execresult
INSERT INTO entries (scope_id, key)
VALUES (?, ?)
`

type InsertEntryParams struct {
	ScopeID int64  `json:"scope_id"`
	Key     string `json:"key"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, InsertEntry, arg.ScopeID, arg.Key)
}

const ListEntriesByScope = `-- name: ListEntriesByScope :many
SELECT id, scope_id, key, created_at
FROM entries
WHERE scope_id = ?
ORDER BY id
`

func (q *Queries) ListEntriesByScope(ctx context.Context, scopeID int64) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, ListEntriesByScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.Key,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
