// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package sqldb

import (
	"context"
)

const DeleteAllEntries = `-- name: DeleteAllEntries :exec
DELETE FROM entries
`

func (q *Queries) DeleteAllEntries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllEntries)
	return err
}

const DeleteAllEntryStatus = `-- name: DeleteAllEntryStatus :exec
DELETE FROM entry_status
`

func (q *Queries) DeleteAllEntryStatus(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllEntryStatus)
	return err
}

const DeleteAllScopes = `-- name: DeleteAllScopes :exec
DELETE FROM scopes
`

func (q *Queries) DeleteAllScopes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllScopes)
	return err
}

const DeleteAllVersions = `-- name: DeleteAllVersions :exec
DELETE FROM versions
`

func (q *Queries) DeleteAllVersions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteAllVersions)
	return err
}
