// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"database/sql"
)

type Entry struct {
	ID        int64        `json:"id"`
	ScopeID   int64        `json:"scope_id"`
	Key       string       `json:"key"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type EntryStatus struct {
	EntryID        int64         `json:"entry_id"`
	IsArchived     sql.NullInt64 `json:"is_archived"`
	CurrentVersion sql.NullInt64 `json:"current_version"`
	UpdatedAt      sql.NullTime  `json:"updated_at"`
}

type Scope struct {
	ID           int64          `json:"id"`
	Type         string         `json:"type"`
	PrimaryPath  sql.NullString `json:"primary_path"`
	WorktreeID   sql.NullString `json:"worktree_id"`
	WorktreePath sql.NullString `json:"worktree_path"`
	BranchName   sql.NullString `json:"branch_name"`
	ScopePath    string         `json:"scope_path"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Version struct {
	ID          int64          `json:"id"`
	EntryID     int64          `json:"entry_id"`
	Version     int64          `json:"version"`
	FilePath    string         `json:"file_path"`
	Hash        string         `json:"hash"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
