// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scope.sql

package sqldb

import (
	"context"
	"database/sql"
)

const DeleteBranchScope = `-- name: DeleteBranchScope :execrows
DELETE FROM scopes
WHERE type = 'branch'
  AND primary_path = ?
  AND branch_name = ?
`

type DeleteBranchScopeParams struct {
	PrimaryPath sql.NullString `json:"primary_path"`
	BranchName  sql.NullString `json:"branch_name"`
}

func (q *Queries) DeleteBranchScope(ctx context.Context, arg DeleteBranchScopeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteBranchScope, arg.PrimaryPath, arg.BranchName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteScopeByID = `-- name: DeleteScopeByID :execrows
DELETE FROM scopes
WHERE id = ?
`

func (q *Queries) DeleteScopeByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteScopeByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteScopesByPrimaryPath = `-- name: DeleteScopesByPrimaryPath :execrows
DELETE FROM scopes
WHERE primary_path = ?
  AND type IN ('repository', 'branch', 'worktree')
`

func (q *Queries) DeleteScopesByPrimaryPath(ctx context.Context, primaryPath sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteScopesByPrimaryPath, primaryPath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const FindScopeByID = `-- name: FindScopeByID :one
SELECT id, type, primary_path, worktree_id, worktree_path, branch_name, scope_path, created_at, updated_at
FROM scopes
WHERE id = ?
LIMIT 1
`

func (q *Queries) FindScopeByID(ctx context.Context, id int64) (Scope, error) {
	row := q.db.QueryRowContext(ctx, FindScopeByID, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.PrimaryPath,
		&i.WorktreeID,
		&i.WorktreePath,
		&i.BranchName,
		&i.ScopePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const FindScopeByPath = `-- name: FindScopeByPath :one
SELECT id, type, primary_path, worktree_id, worktree_path, branch_name, scope_path, created_at, updated_at
FROM scopes
WHERE scope_path = ?
LIMIT 1
`

func (q *Queries) FindScopeByPath(ctx context.Context, scopePath string) (Scope, error) {
	row := q.db.QueryRowContext(ctx, FindScopeByPath, scopePath)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.PrimaryPath,
		&i.WorktreeID,
		&i.WorktreePath,
		&i.BranchName,
		&i.ScopePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertScope = `-- name: InsertScope :execresult
INSERT INTO scopes (type, primary_path, worktree_id, worktree_path, branch_name, scope_path)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertScopeParams struct {
	Type         string         `json:"type"`
	PrimaryPath  sql.NullString `json:"primary_path"`
	WorktreeID   sql.NullString `json:"worktree_id"`
	WorktreePath sql.NullString `json:"worktree_path"`
	BranchName   sql.NullString `json:"branch_name"`
	ScopePath    string         `json:"scope_path"`
}

func (q *Queries) InsertScope(ctx context.Context, arg InsertScopeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, InsertScope,
		arg.Type,
		arg.PrimaryPath,
		arg.WorktreeID,
		arg.WorktreePath,
		arg.BranchName,
		arg.ScopePath,
	)
}

const ListScopes = `-- name: ListScopes :many
SELECT id, type, primary_path, worktree_id, worktree_path, branch_name, scope_path, created_at, updated_at
FROM scopes
ORDER BY type, primary_path, branch_name
`

func (q *Queries) ListScopes(ctx context.Context) ([]Scope, error) {
	rows, err := q.db.QueryContext(ctx, ListScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scope
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PrimaryPath,
			&i.WorktreeID,
			&i.WorktreePath,
			&i.BranchName,
			&i.ScopePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateScope = `-- name: UpdateScope :exec
UPDATE scopes
SET type = ?,
    primary_path = ?,
    worktree_id = ?,
    worktree_path = ?,
    branch_name = ?,
    scope_path = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScopeParams struct {
	Type         string         `json:"type"`
	PrimaryPath  sql.NullString `json:"primary_path"`
	WorktreeID   sql.NullString `json:"worktree_id"`
	WorktreePath sql.NullString `json:"worktree_path"`
	BranchName   sql.NullString `json:"branch_name"`
	ScopePath    string         `json:"scope_path"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateScope(ctx context.Context, arg UpdateScopeParams) error {
	_, err := q.db.ExecContext(ctx, UpdateScope,
		arg.Type,
		arg.PrimaryPath,
		arg.WorktreeID,
		arg.WorktreePath,
		arg.BranchName,
		arg.ScopePath,
		arg.ID,
	)
	return err
}
